// Assemble the tuned per-sound recipes into src/js/content/sounds-data.js
// (the data the in-browser synth interpreter, content/sounds.js, plays).
// Usage: node tools/audio/harvest.mjs [recipesDir]
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const recipesDir = process.argv[2] || join(here, 'recipes');
const out = join(here, '..', '..', 'src', 'js', 'content', 'sounds-data.js');

const files = readdirSync(recipesDir).filter((f) => f.endsWith('.json')).sort();
const recipes = {};
for (const f of files) {
  const name = f.replace(/\.json$/, '');
  recipes[name] = JSON.parse(readFileSync(join(recipesDir, f), 'utf8'));
}

const body = `/**
 * Synth recipes per sound name (the DSL interpreted by content.sounds).
 *
 * GENERATED by tools/audio/harvest.mjs from tools/audio/recipes/*.json. Each
 * recipe was designed and spectrally tuned against the original Curb Game
 * sample's measured features (centroid, flatness, band energy, dominant peaks)
 * by the curb-synth-design workflow. Do not hand-edit; edit the recipe sources
 * and re-run the harvest. See tools/audio/README.md.
 */
content.soundRecipes = ${JSON.stringify(recipes, null, 2)}
`;

writeFileSync(out, body);
console.log(`wrote ${out} with ${files.length} recipes`);
